name: "microservices-demo"

services:

###################################################
#  Services
###################################################

  customers-api:
    image: ${DOCKER_REGISTRY-}customersapi
    build:
      context: .
      dockerfile: src/Services/Customers/src/Customers.Api/Dockerfile

  promotions-api:
    image: ${DOCKER_REGISTRY-}promotionsapi
    build:
      context: .
      dockerfile: src/Services/Promotions/src/Promotions.Api/Dockerfile

  accounting-api:
    image: ${DOCKER_REGISTRY-}accountingapi
    build:
      context: .
      dockerfile: src/Services/Accounting/src/Accounting.Api/Dockerfile

  emailsender:
    image: ${DOCKER_REGISTRY-}emailsender
    build:
      context: .
      dockerfile: src/Services/EmailSender/src/EmailSender/Dockerfile

  healthcheck:
    image: ${DOCKER_REGISTRY-}healthcheck
    build:
      context: .
      dockerfile: src/WebApps/HealthCheck/Dockerfile

###################################################
#  Infrastructure
###################################################

  sql-server:
    container_name: sql-server-msdi
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    ports:
      - "7433:1433"
    environment:
      SA_PASSWORD: "str0ngp@ssword"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/home/sql/data

  rabbitmq:
    container_name: rabbitmq-msdi
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 7672:5672
      - 17672:15672
    volumes:
      - rabbitmq_data:/home/rabbitmq/data
    
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger-msdi
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686

  seq:
    image: datalust/seq:latest
    container_name: seq-msdi
    restart: unless-stopped
    ports:
      - '7341:80'
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/home/seq/data

###################################################
#  Volumes
###################################################

volumes:
  sql_data:
  rabbitmq_data:
  seq_data:


