version: "3.3"
name: "microservices-demo-infrastructure"

services:

    #######################################################
    #  Sql-server
    #######################################################
  sql-server-db:
    container_name: sql-server-msdi
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "str0ngp@ssword"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/home/sql/data

    #######################################################
    #  Rabbitmq
    #######################################################
  rabbitmq:
    container_name: rabbitmq-msdi
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/home/rabbitmq/data
    
    #######################################################
    #  Jaeger
    #######################################################
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger-msdi
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686

    #######################################################
    #  Seq
    #######################################################
  seq:
    image: datalust/seq:latest
    container_name: seq-msdi
    ports:
      - '5341:80'
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/home/seq/data

volumes:
  sql_data:
  rabbitmq_data:
  seq_data:
